name: Build

on:
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android libbox.aar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Set up Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28-beta2

      - name: Set up OpenJDK
        run: |
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version

      - name: Build libbox.aar
        run: |
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload libbox.aar
        uses: actions/upload-artifact@v4
        with:
          name: "libbox.aar"
          path: libbox.aar
